##############################################
# multy langueage 
##############################################
#기본 언어 tag 
m_language_base=ko
#생성할 언어 tag 
m_language_type=ko,en

#번역을 위한 사전파일 컨피그 파일과 같이 있어야 한다. 
#형식은 json형식이여야 합니다. 
m_dic_file_name=dic.lang.json

#JDBC DBMS Connecting 
driverClassName=
url=
username=
password=

