#

##############################################
# Basic Tag 
##############################################
#일반컨트롤 코멘트 기본테그
C_CONTROL_TAG=<ROW>\
               <r>E-NAME:\
               <r>E-DOC:\
               <r>E-PARAM:\
               <r>E-RR-UI-NAME:\
               <r>E-CALL-SRV-NAME:\
               <r>E-REP:\
               <r>E-REMARK:
#app 코멘트 기본테그
C_APP_TAG=<p>SYSTEM:\
          <p>SUB-SYSTEM:\
          <p>RUN-TYPE:\
          <p>UI-ID:\
          <p>UI-NAME:\
          <p>CRUD:\
          <p>UI-COMMENT:\
          <p>UI-REMARK:\
          <p>UI-COMMENT: