#is run stand alone 

##############################################
#  CLX QC 
##############################################
M_TAB_TO_SPACE_CNT=4
M_READ_FILE_ENCODE=UTF-8
M_WRITE_FILE_ENCODE=UTF-8