#is run stand alone 

##############################################
#  sample 
##############################################
# app comment 
##############################################
#<p>SYSTEM: COMMMON 
#<p>SUB-SYSTEM: MENU
#<p>RUN-TYPE: MDI CONTENTS
#<p>UI-ID:  AAA0010
#<p>UI-NAME: MENU MGR
#<p>CRUD:
#<p>UI-COMMENT: COMMENT AAAA
#<p>UI-REMARK:
#<p>UI-COMMENT:
##############################################
# controle comment 
##############################################
#<ROW>
#<r>E-NAME: 
#<r>E-DOC:   
#<r>E-PARAM: 
#<r>E-RR-UI-NAME: 
#<r>E-CALL-SRV-NAME: 
#<r>E-REP:
#<r>E-REMARK:  
#<ROW>
#<r>E-NAME: 
#<r>E-DOC:  
#<r>E-PARAM:  
#<r>E-RR-UI-NAME: 
#<r>E-CALL-SRV-NAME: 
#<r>E-REP:
#<r>E-REMARK:  


#############################################
# EXCEL CONFIG 
# M_BASE_FILE : 엑셀 전환 기준 파일
# M_OUT_FILE_EXCEL_NAME : 전환될 엑셀파일명 , 대괄호 []는 <P>item의 값으로 치환된다. 
# M_OUT_FILE_EXCEL_PATH : 생성될 엑셀파일위치 
#############################################
M_BASE_FILE=/docinfo/UI_BASE_CTL.xlsx
M_OUT_FILE_EXCEL_NAME=TOMATO_[SUB-SYSTEM]_DS_화면설계서([UI-ID]_[UI-NAME])_V1.1.xlsx
M_OUT_FILE_EXCEL_PATH=docexcel/..

#############################################
# Default value N ( STD 에 적용 )
# TAG를 fix 한다. 
#  <ROW> 1개의 row를 증가시킨다. 
#  <FIX> row를 증가시키지 않는다. ( 첫줄을 생략한다.)
#  <P> : single item , <R> : row item 
#############################################
M_TAG_FIX_YN=Y

M_TAG_ROW=<ROW>
M_TAG_ROW_ITEM=<R>
M_TAG_FIX=<FIX>
M_TAG_FIX_ITEM=<P>

#############################################

#############################################
# PAGE Information 
# 사용 미확정 
#############################################
M_MAIN_CONTENT_SHEET_NAME=화면설계서
M_MAIN_CONTENT_SHEET_TAG=<ROW>
M_MAIN_IMG_TAG=<IMAGE>
#SHEET 추가 ( 2020-08-26 )
M_SUB_CONTENT_SHEET_NAME=컨트롤리스트
M_SUB_CONTENT_SHEET_TAG=<ROWCTL>

#############################################
# SUBMISSION MTX ORI SHEET NAME
# SEQUNCE NO => SUBMIT_SYS_NO
#############################################
SUBMIT_SHEET_NAME=submition_sample
SUBMIT_SHEET_NEW_NAME=itfId
SUBMIT_SHEET_NEW_NAME_DEFAULT=PROTOCLAL
SUBMIT_SHEET_M_SUB=SUBMISSION
SUBMIT_SHEET_M_REQ=request
SUBMIT_SHEET_M_REP=response
SUBMIT_SYS_NO=<SY_NO>
SUBMIT_CHK_ATTR=lvl


#############################################
# To Excel(DataModule)
# M_DATA_MODULE_BASE_FILE : 엑셀 전환 기준 파일
# M_DATA_MODULE_OUT_FILE_EXCEL_NAME : 전환될 엑셀파일명 , 대괄호 []는 <P>item의 값으로 치환된다. 
# M_DATA_MODULE_OUT_FILE_EXCEL_PATH : 생성될 엑셀파일위치 
#
#M_DATA_MODULE_DATASET_TITLE_YN : 데이터셋 항목 타이틀 출력 여부
#M_DATA_MODULE_DATASET_TITLE    : 데이터셋 항목 타이틀 명
#
#M_DATA_MODULE_DATAMAP_TITLE_YN : 데이터셋 항목 타이틀 출력 여부
#M_DATA_MODULE_DATAMAP_TITLE    : 데이터셋 항목 타이틀 명
#
#M_DATA_MODULE_SUBMIT_TITLE_YN  : 데이터셋 항목 타이틀 출력 여부
#M_DATA_MODULE_SUBMIT_TITLE     : 데이터셋 항목 타이틀 명
#
#M_DATA_MODULE_DEFAULT_SPACING  : 기본 스페이싱 1칸 보다 많을 경우 설정 
#
#############################################
M_DATA_MODULE_BASE_FILE=/docinfo/UI_BASE_DATA_MODULE.xlsx
M_DATA_MODULE_OUT_FILE_EXCEL_NAME=TOMATO_[SUB-SYSTEM]_DS_화면설계서([UI-ID]_[UI-NAME])_V1.1.xlsx
M_DATA_MODULE_OUT_FILE_EXCEL_PATH=docexcel/..

M_DATA_MODULE_DATASET_TITLE_YN=Y
M_DATA_MODULE_DATASET_TITLE=데이터셋 리스트

M_DATA_MODULE_DATAMAP_TITLE_YN=Y
M_DATA_MODULE_DATAMAP_TITLE=데이터맵 리스트

M_DATA_MODULE_SUBMIT_TITLE_YN=Y
M_DATA_MODULE_SUBMIT_TITLE=서브미션 리스트

M_DATA_MODULE_DEFAULT_SPACING=1

#############################################
# To Excel(DataModule) 정보 맵핑
# M_DATA_MODULE_ 뒤로부터 excel에 정의한 태그를 기준으로 정보를 읽어와 뿌려준다.
# 읽어오는 값으로는 #{clx테그정보} 를 입력하면 해당 영역에 맞는 데이터를 가져와 뿌려준다.
# M_DATA_MODULE_~~_NA= 값이 null인 경우 세팅해줄 값을 지정한다.
# 일부 고정값을 지원하는 항목 displayonly, datatype 등은 기본 세팅되는 값으로 인해 NA지원이 불가능하다.
#
# 현재 지원하는 데이터는 M_DATA_MODULE_DATASET_~ 와 M_DATA_MODULE_DATAMAP_~ 만 지원한다.
#
# *submission은 고정된 테그만 지원한다.
# 지원하는 submit 테그
# 서브밋 기본정보: <SUBMIT_ID>,<SUBMIT_ACTION>
# 서브밋 요청데이터:<SUBMIT_REQ_DATA_ID>,<SUBMIT_REQ_ALIAS>,<SUBMIT_REQ_PAYLOAD>
# 서브밋 응답데이터:<SUBMIT_RES_DATA_ID>,<SUBMIT_RES_ALIAS>,<SUBMIT_RES_PAYLOAD>
#############################################
M_DATA_MODULE_DATASET_ID=#{id} : #{comment}
#M_DATA_MODULE_DATASET_COMMENT=#{comment}
#M_DATA_MODULE_DATASET_INFO=#{info}
#M_DATA_MODULE_DATASET_SORT_CONDITION=#{sortcondition}
#M_DATA_MODULE_DATASET_FILTER_CONDITION=#{filtercondition}
#M_DATA_MODULE_DATASET_ALTER_COLUMN_LAYOUT=#{altercolumnlayout}
#M_DATA_MODULE_DATASET_STATE_RESTORE=#{state_restore}

M_DATA_MODULE_DATASET_COLUMN_NAME=#{name}
M_DATA_MODULE_DATASET_COLUMN_DATATYPE=#{datatype}
M_DATA_MODULE_DATASET_COLUMN_EXPRESSION=#{expression}
M_DATA_MODULE_DATASET_COLUMN_EXPRESSION_NA=N/A
M_DATA_MODULE_DATASET_COLUMN_DISPLAYONLY=#{displayonly}
M_DATA_MODULE_DATASET_COLUMN_INFO=#{info}
M_DATA_MODULE_DATASET_COLUMN_INFO_NA=(None)
M_DATA_MODULE_DATASET_COLUMN_COMMENT=#{comment}
M_DATA_MODULE_DATASET_COLUMN_COMMENT_NA=(None)

#DATAMAP_ID,DATAMAP_TYPE,DATAMAP_COMMENT,DATAMAP_INFO,DATAMAP_SORT_CONDITION,DATAMAP_FILTER_CONDITION,DATAMAP_ALTER_COLUMN_LAYOUT,DATAMAP_STATE_RESTOREDATAMAP_COLUMN_NAME,DATAMAP_COLUMN_DATATYPE,DATAMAP_COLUMN_EXPRESSION,DATAMAP_COLUMN_DISPLAY_ONLY,DATAMAP_COLUMN_INFO,DATAMAP_COLUMN_COMMENT
M_DATA_MODULE_DATAMAP_ID=#{id} : #{comment}
#M_DATA_MODULE_DATAMAP_COMMENT=#{comment}
#M_DATA_MODULE_DATAMAP_INFO=#{info}
#M_DATA_MODULE_DATAMAP_ALTER_COLUMN_LAYOUT=#{altercolumnlayout}

M_DATA_MODULE_DATAMAP_COLUMN_NAME=#{name}
M_DATA_MODULE_DATAMAP_COLUMN_DATATYPE=#{datatype}
M_DATA_MODULE_DATAMAP_COLUMN_EXPRESSION=#{expression}
M_DATA_MODULE_DATAMAP_COLUMN_EXPRESSION_NA=N/A
M_DATA_MODULE_DATAMAP_COLUMN_DEFAULTVALUE=#{defaultvalue}
M_DATA_MODULE_DATAMAP_COLUMN_DEFAULTVALUE_NA=(None)
M_DATA_MODULE_DATAMAP_COLUMN_INFO=#{info}
M_DATA_MODULE_DATAMAP_COLUMN_INFO_NA=(None)
M_DATA_MODULE_DATAMAP_COLUMN_COMMENT=#{comment}
M_DATA_MODULE_DATAMAP_COLUMN_COMMENT_NA=(None)

#SUBMIT_ID,SUBMIT_TYPE,SUBMIT_COMMENT,SUBMIT_INFO,SUBMIT_ACTION,SUBMIT_ASYC,SUBMIT_WITH_CREDENTIALS,SUBMIT_REQ_DATA_ID,SUBMIT_REQ_ALIAS,SUBMIT_REQ_PAYLOAD,SUBMIT_RES_DATA_ID,SUBMIT_RES_ALIAS,SUBMIT_RES_ADD
#서브미션은 예외처리 사항이 많기에 현재 사용중이지않음.
#M_DATA_MODULE_SUBMIT_ID=#{id}
#M_DATA_MODULE_SUBMIT_COMMENT=#{comment}
#M_DATA_MODULE_SUBMIT_INFO=#{info}
#M_DATA_MODULE_SUBMIT_ACTION=#{action}
#M_DATA_MODULE_SUBMIT_ASYC=#{asyc}
#M_DATA_MODULE_SUBMIT_WITH_CREDENTIALS=#{with_credentials}
#
#M_DATA_MODULE_SUBMIT_REQ_DATA_ID=#{data_id}
#M_DATA_MODULE_SUBMIT_REQ_ALIAS=#{alias}
#M_DATA_MODULE_SUBMIT_REQ_PAYLOAD=#{payload}
#
#M_DATA_MODULE_SUBMIT_RES_DATA_ID=#{data_id}
#M_DATA_MODULE_SUBMIT_RES_ALIAS=#{alias}
#M_DATA_MODULE_SUBMIT_RES_ADD=#{isadd}


#############################################
# HTML CONFIG & XML
#M_OUT_FILE_XML_PATH & M_OUT_FILE_XML_PATH  [.][/aaaaa][/aaaaa/..]
#############################################
M_BASE_HTML_FILE=/docinfo/UI_BASE1.html

M_HTML_GRID_TAG=clx:grid:row>
M_HTML_CELL_TAG=clx:cell:row>
M_HTML_CMT_TAG=clx:cmt:row>
M_HTML_SUB_TAG=clx:submition:row>
M_HTML_IMG_TAG=[UI-IMAGE]

#ROWNUM , CHECK CELL IGNORE 
M_GRID_IGNORE_SPCELL=Y

#APPLY FARST EXCEL FILE
#<CONF:OUT-FILE-NAME>HLICP_[SUB-SYSTEM]_DS_화면설계서([UI-ID]_[UI-NAME])_V1.1.xlsx
#<CONF:OUT-FILE-PATH>docinfo

M_OUT_FILE_HTML_NAME=TOMATO_[SUB-SYSTEM]_DS_화면설계서([UI-ID]_[UI-NAME])_V1.1.html
M_OUT_FILE_HTML_PATH=dochtml/..
M_OUT_FILE_XML_PATH=docxml/..

#N/A config a
M_NA=NONE
#NO HAVE ELEMENT ( #DEFALUT VALUE : N/A ) - NONE -> 무표시 
M_NONE_ELELMENT=NONE
#M_NONE_ELELMENT=N/A
#N/A TAG NAME을 콤마로 분리하여 정의한다. 혹은 기준 엑셀의 TAG : <EVNT-NAME> 을 <NAME-NAME.NONE>으로 정의해도 
#같은 효과가 생긴다. ( 값이 없을 경우 N/A의 값을 넣지 않을 TAG정의 ) NONE -> 무표시 
M_NA_TEMP=TEMP-NOT-USE
M_NA_IGNORE=E-CALL-SRV-NAME1,U_EDIT,P-GRID-ID,P-META-KOR,P-ID,

#이벤트 관련 소트 기준 
#EVENT_SORT_NONE : 소트키가 없을 경우 90으로 생성한다. 
#SORT를 하지않으려면 EVENT_SORT_KEY=NONE으로 처리 
EVENT_SORT_FST=1
EVENT_SORT_LST=99
EVENT_SORT_NONE=90
#EVENT_SORT_KEY=SORT_INDEX
EVENT_SORT_KEY=NONE

#SORT 순서를 정하지 않았을 경우 자동으로 내부적으로 sort key를 작성한다. 
#EVENT_SORT_NONE_KEY_NAME : 기준키 
#EVENT_SORT_NONE_FST_NAME : 1로우  ( 해당값일 경우 sort key를 1로 생성 )
#EVENT_SORT_NONE_LST_NAME : 마지막로우 ( 해당값일 경우 sort key를 99로 생성 )
EVENT_SORT_NONE_KEY_NAME=E-NAME
EVENT_SORT_NONE_FST_VALUE=화면로드
EVENT_SORT_NONE_LST_VALUE=화면언로드


#############################################
# controle list 2023.01.01
# CONTROLE_FILTER_CONDITION: 선택할 controle filter 조건 ( and 조건 컴마 분리 ) ID,COMMENT,BUTTON
# CONTROLE_LIST_YN : 설계서에 컨트롤 리스트 포함여부 
# CONTROLE_IGNORE_TYPES : 제외 컨트롤 타입
# CONTROLE_EDIT_TYPES : 에디터 가능한 대상 
# CONTROLE_EDIT_MARK : 에대터 가능한 상태일 경우 표시 문자 정의 
#############################################
CONTROLE_LIST_YN=Y
CONTROLE_SHEET_NAME=컨트롤리스트
CONTROLE_FILTER_CONDITION=P-ID
#Controle list를 작성할때 제외할 항목 
CONTROLE_IGNORE_TYPES=,group,
#특정값이 없으면 제외할 항목 
CONTROLE_IGNORE_VALUE_NULL=P-ID
#특정값이 true이면 제외할 항목 
CONTROLE_IGNORE_VALUE_TRUE=P-RMBUILD
#특정값이 FALSE 이면 제외할 항목 
CONTROLE_IGNORE_VALUE_FALSE=P-RMBUILD2
#editorble controle list
CONTROLE_EDIT_TARGET_TAG=P-NDTYPE
CONTROLE_EDIT_TYPES=,grid,textara,inputbox,numbereditor,numbereditor,searchinput,combobox,radiobutton,dateinput,listbox,navigationbar,linkedlistbox,linkedcombobox,maskeditor,menu,slider,checkbox,checkboxgroup,combobox,textarea,tree,fileinput,
#editorble charter
CONTROLE_EDIT_MARK=E
CONTROLE_EDIT_MARK_TAG=U_EDIT
# : 뒤의 값은 condition true 값 
CONTROLE_EDIT_MARK_CONDITION=P-READONLY:false,P-ENABLED:true
# 그리드내의 컨트롤의 grid ID
CONTROLE_PARENT_GRID_ID=P-GRID-ID
# 그리드내의 컨트롤 value 변경 ( CONTROL-PROPERTY : CELL-PROPERTY )
CONTROLE_PARENT_CELL_VALUE=P-ID:C-COLUMN,P-COLINDEX:P-COLINDEX,P-ROWINDEX:P-ROWINDEX

 

#############################################
# DEV STS CONFIG (HTML)
#############################################

#DEVELOPER PROGRASS CONFIG
M_DEV_STS_HTML_FILE=/docinfo/UI_BASE_STATUS.html

#DEVELOPER PROGRASS CONFIG STATUS 
#M_DEV_STS_01_START     : End of mack Clx file  
#M_DEV_STS_01_DSTART    : Start of Document wright
#M_DEV_STS_01_DCOMMIT   : End of document wright 
#M_DEV_STS_01_DEV       : Development
#M_DEV_STS_01_UNIT_TEST : End of UNIT TEST 
#M_DEV_STS_01_COMMIT    : End of JOB
M_DEV_STS_01_START=START
M_DEV_STS_01_DSTART=DOC_START
M_DEV_STS_01_DCOMMIT=DOC_COMMIT
M_DEV_STS_01_DEV=DEV_ING
M_DEV_STS_01_UNIT_TEST=UTEST
M_DEV_STS_01_COMMIT=COMMIT
M_DEV_STS_01_DELETE=DEL 
M_DEV_STS_01=M_DEV_STS_01_START,M_DEV_STS_01_DSTART,M_DEV_STS_01_DCOMMIT,M_DEV_STS_01_DEV,M_DEV_STS_01_UNIT_TEST,M_DEV_STS_01_COMMIT
M_DEV_STS_PATH=DIRPATH

M_HTML_STS_TAG=clx:sts:row>

#APP PROPERTY NAME
M_DEV_STS_APP_PROP=DEV_STATUS
M_DEV_STS_TOTCNT=TOT_CNT_CLX

M_STS_FILE_NAME=DEV_STS_0101.html

#############################################

#OUTPUT DOCUMENT
M_FILE_TYPE=XML


#UDC ( Y( UDC 내부 내역 ), N( 내부내역 표현 안함  ) - don't user this attribute
M_UDC_APPLY=Y

#############################################
# EXCEL,HTML,XNL CONFIG 
#############################################
#{P-NDTYPE       ,ATT||NODENM||--||CELL},     \
#abstruct config 
M_CONTROLS_ABSTRUCT={{P-ID         ,ATT||id||--||--},           \
                   {P-NDTYPE       ,NDNM||--||--||--},      \
                   {P-TYPE         ,NDNM||--||--||--},      \
                   {P-NAME         ,ATT||fieldLabel||--||--},   \
                   {P-VALUE        ,ATT||value||--||--},   \
                   {P-READONLY     ,ATT||readonly||--||--},   \
                   {P-ENABLED      ,ATT||enabled||--||--},   \
                   {P-VISIBLE      ,ATT||visible||--||--},   \
                   {P-TEXT         ,ATT||text||--||--},   \
                   {P-META-ENG     ,UAT||VALUE||META-ENG||--},   \
                   {P-META-KOR     ,UAT||VALUE||META-KOR||--},   \
                   {P-DATA_TYPE    ,UAT||VALUE||DATA-TYPE||--},   \
                   {P-LENGTH       ,ATT||length||--||--},   \
                   {P-FORMAT       ,ATT||format||--||--},   \
                   {P-CODE_YN      ,UAT||VALUE||CODE_YN||--},   \
                   {P-REQ_YN       ,UAT||VALUE||required||--},   \
                   {P-PATH         ,ATT||path||--||--},   \
                   {P-RMBUILD      ,ATT||removeOnBuild||--||--},   \
                   {P-BIND         ,ATT||BIND||--||--},   \
                   {P-RER          ,CMT||*||--||--}}
                   
                   

M_COMMENT_MAIN=          {{P_UI_ID      ,FILE||FILENM||--||--},      \
                         {P_UI_NM       ,BODY||TITLE||--||--},      \
                         {P_REMARK      ,APCMT||TEXT||--||--},      \
                         {P_PGM_TYPE    ,APCMT||TEXT||--||--},      \
                         {P_UNIT_SYSTEM_CD ,APCMT||P_UNIT_SYSTEM_CD||--||--},      \
                         {P_SUB_SYSTEM_CD  ,APCMT||P_SUB_SYSTEM_CD||--||--}} 


#<EVNET TAG <EVENT> tag로 시작하면 이를 이벤트로 본다. 
M_EVENT=                {{E-NAME        ,APCMT||E-NAME||--||--},      \
                         {E-DOC         ,APCMT||E-DO||--||--},      \
                         {E-PARAM       ,APCMT||E-PARAM||--||--},      \
                         {E-RR-UI-NM    ,APCMT||E-RR-UI-NM||--||--},      \
                         {E-CALL-NM     ,APCMT||E-CALL-NM||--||--},      \
                         {E-REP         ,APCMT||E-RE||--||--},      \
                         {E-REMARK      ,APCMT||E-REMARK||--||--}} 



#############################################
#control config 
# ATT(PROPERTY) || TEXT ( PROPERTY KEY ) ||-- (노드 속성중 명  key ) ||-- ( 하위노드 )    
# CMT(COMMENT)  || TEXT ( 전체 ) , P-APP ( <P>P-APP: 이후의 내역 ) , * ( key 동일 ) ||--||--
# NDNM NODE NAME
# PNDNM Parent Node Name 
#############################################


#GRID


#GRID
#M_CONTROLS_GRID={{P-ID           ,ATT||ID||--||--},           \
#                 {P-NAME         ,ATT||fieldLabel||--||--},      \
#                 {P-CRUD_TYPE    ,CMT||*||--||--},      \
#                 {P-COMMENT      ,CMT||*||--||--},      \
#                 {P-TABLE        ,CMT||*||--||--},    \
#                 {C-NAME         ,ATT||TEXT||--||CELL},      \
#                 {C-TYPE         ,ATT||NODENM||--||CELL},      \
#                 {C-COLUMN       ,ATT||columnname||--||CELL},      \
#                 {C-REQ          ,UAT||VALUE||required||CELL},      \
#                 {C-COMMENT      ,CMT||*||--||CELL}}
             
             
#GRID
M_CONTROLS_GRID={{P-CRUD_TYPE    ,CMT||*||--||--},      \
                 {P-COMMENT      ,CMT||*||--||--},      \
                 {P-TABLE        ,CMT||*||--||--}}
                    

#GRID CELL
M_CONTROLS_CELL={{C-NAME         ,ATT||TEXT||--||--},      \
                 {C-TYPE         ,NDNM||--||--||--},      \
                 {P-NDTYPE       ,NDNM||--||--||--},      \
                 {P-POSITION     ,PNDNM||--||--||--},      \
                 {P-ID           ,ATT||columnname||--||--},      \
                 {C-COLUMN       ,ATT||columnname||--||--},      \
                 {P-TYPE         ,ATT||TYPE||--||--},        \
                 {P-COLINDEX     ,ATT||rowindex||--||--},        \
                 {P-ROWINDEX     ,ATT||colindex||--||--},        \
                 {P-COLSPAN      ,ATT||colspan||--||--},        \
                 {P-ROWSPAN      ,ATT||rowspan||--||--},        \
                 {C-REQ          ,UAT||VALUE||required||--},      \
                 {C-COMMENT      ,CMT||*||--||--}}
                    
                    
#SINGLE OBJECT                         
M_CONTROLS_SINGLE={{P-ID           ,ATT||ID||--||--},           \
                   {P-NDTYPE       ,NDNM||--||--||--},      \
                   {P-NAME         ,ATT||fieldLabel||--||--},   \
                   {P-TYPE         ,ATT||TYPE||--||--},        \
                   {PARAM          ,CMT||*||--||--},   \
                   {E-DOC          ,CMT||*||--||--}}
                   
                   
#TAB OBJECT                         
M_CONTROLS_TABFOLDER={{P-ID           ,ATT||ID||--||--},           \
                   {P-NDTYPE       ,NDNM||--||--||--},      \
                   {P-NAME         ,ATT||fieldLabel||--||--},   \
                   {P-TYPE         ,ATT||TYPE||--||--},        \
                   {PARAM          ,CMT||*||--||--},   \
                   {E-DOC          ,CMT||*||--||--}}
                   
#                   {E-NAME         ,ATT||VALUE||--||--},   \
                   
#IMPUT 계열                   
M_CONTROLS_INPUT={{P-ID            ,ATT||ID||--||--},           \
                   {P-NDTYPE       ,NDNM||--||--||--},     \
                   {P-NAME         ,ATT||fieldLabel||--||--},   \
                   {P-NAME         ,ATT||fieldLabel||--||--},   \
                   {P-COMMENT      ,CMT||*||--||--},            \
                   {P-RER          ,CMT||*||--||--}}

#IMPORT
M_IMPORT_UDC={{P-ID             ,ATT||ID||--||--},          \
                 {P-NDTYPE       ,NDNM||--||--||--},      \
                 {P-COMMENT      ,CMT||*||--||--},           \
                 {P-TYPE         ,ATT||TYPE||--||--},        \
                 {C-REMARK       ,CMT||--||--||--},        \
                 {C-CONDITION    ,APCMT||*||--||--}}
                         
                         
                         
                         
                         