##############################################
#Javascript file Minify Config
# ver 1.0 
##############################################
#
##############################################
# Basic Tag 
##############################################
#
#	public class Options {
#
#	    public String charset = "UTF-8";
#	    public int lineBreakPos = -1;
#	    public boolean munge = true;
#	    public boolean verbose = false;
#	    public boolean preserveAllSemiColons = false;
#	    public boolean disableOptimizations = false;
#	    
#	}
#
#

#source Tag 
SOURCE_TAG=.js

#target Tag
TARGET_TAG=.min.js

#option 
OPTION_CHAR_SET=UTF-8
OPTION_LINE_BREAK_POS=-1
OPTION_MUNGE=true
OPTION_VERBOSE=false
OPTION_ALL_SEMI=false
OPTION_DE_OPTIMI=false
